apiVersion: v1
kind: Service
metadata:
  name: fe-service
  labels:
    app: fe-service
spec:
  ports:
  - port: 3000
    protocol: TCP
    nodePort: 32321
  type: NodePort  
  selector:
    tier: front-end
