apiVersion: v1
kind: Service
metadata:
  name: be-service
  labels:
    app: be-service
spec:
  ports:
  - port: 8080
    protocol: TCP
    nodePort: 32322
  type: NodePort  
  selector:
    tier: back-end
